name: Deploy Site
on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build Homesite
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setting up pnpm
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.0.2
                  run_install: true
            - name: Building Project
              run: pnpm build
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./build
