name: Deploy Site
on:
    push:
        branches:
            - source

jobs:
    build:
        name: Build Svelte Site
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '16.x'
            - name: Install dependencies
              run: yarn
            - name: Build
              run: yarn build
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.ACCESS_TOKEN }}
                  publish_dir: ./build
